### ISSUE TITLE
PartialOrd behaviour

### ISSUE THREAD

**Issue by DenisKolodin** [stainless-steel/probability#13]
Lib contains comparsions like:

``` rust
impl distribution::Continuous for Exponential {
    #[inline]
    fn density(&self, x: f64) -> f64 {
        if x < 0.0 {
            0.0
        } else {
            self.lambda * (-self.lambda * x).exp()
        }
    }
}
```

but in fact `f64` implements `PartialOrd` only and comparsion contains some uncontrolled behaviour:

```
if x < 0.0 {
    0.0
} else {   // x >= 0.0 && x.is_nan()
    self.lambda * (-self.lambda * x).exp()
}
```

What about to use `PartialCmp` explicitly? I think It won't decline perfomance.

**Comment by IvanUkhov** [comment]
So the second branch will be taken not only when `x` is nonnegative but also when `x` is NaN. If `x` is NaN, a reasonable thing to do is to output NaN, and this is exactly what the current implementation does. I’m not sure what you would like to do instead. Could you please give an example?

**Comment by IvanUkhov** [comment]
It’s actually an interesting observation. To be honest, I never thought about NaNs when I wrote that code. In the example you gave, it works just because the code is structured in this particular way. If it was the other way around like so

```rust
if x >= 0.0 {
     self.lambda * (-self.lambda * x).exp()
} else {
    0.0
}
```

it would return zero instead of NaN. Perhaps I should check all the comparisons in the code. Thanks for drawing attention to this!

**Comment by DenisKolodin** [comment]
Great example! I mean this. I think we have to use something robust like:
```rust
match x.partial_cmp(&0) {
    Some(Grater) | Some(Equal) => self.lambda * (-self.lambda * x).exp(),
    Some(Less) => 0.0,
    None => f64::NaN,
}
```

I've found that when take bugs with `Triangular`.

**Comment by IvanUkhov** [comment]
I guess you’re referring to this and to a couple of other functions:

```rust
impl distribution::Continuous for Triangular {
    fn density(&self, x: f64) -> f64 {
        use std::f64;
        use std::cmp::Ordering::*;
        if x <= self.a {
            0.0
        } else if self.b <= x {
            1.0
        } else {
            let diff = self.b - self.a;
            match x.partial_cmp(&self.c) {
                Some(Less) | Some(Equal) => (x - self.a).powi(2) / diff / (self.c - self.a),
                Some(Greater) => 1.0 - (self.b - x).powi(2) / diff / (self.b - self.c),
                None => f64::NAN,
            }
        }
    }
}
```

So the point is to explicitly capture NaNs, and I perfectly understand this concern. However, I’m thinking that there should be a less intrusive way of handling this. I’m afraid that such overly verbose constructions will appear everywhere and simply obscure the code.

The problem with NaNs stems from input arguments. We could, for instance, introduce a small macro that will check the arguments for NaNs and, if found any, return a NaN. Similar to what `should!` currently does (but it panics instead of returning). For instance:

```rust
macro_rules! nonnan(
    ($argument:ident) => (if $argument.is_nan() { return ::std::f64::NAN; });
);

impl distribution::Continuous for Triangular {
    fn density(&self, x: f64) -> f64 {
        nonnan!(x);
        if x <= self.a {
            0.0
        } else if self.b <= x {
            1.0
        } else {
            let diff = self.b - self.a;
            if x <= self.c {
                (x - self.a).powi(2) / diff / (self.c - self.a)
            } else {
                1.0 - (self.b - x).powi(2) / diff / (self.b - self.c)
            }
        }
    }
}
```

What are your thoughts about this?

**Comment by DenisKolodin** [comment]
Conditions becomes fully predictable with removal of NaN. Also It looks more tidy instead of patterns matching. Can I add this macro with #12 PR?

**Comment by IvanUkhov** [comment]
Yes, absolutely, but don’t use it anywhere else except for the new code. We’ll introduce it gradually in the rest of the code base. Thanks!
