### ISSUE TITLE
Add `new_with_check` methods to distributions

### ISSUE THREAD

**Issue by DenisKolodin** [stainless-steel/probability#17]
There aren't constructors which returns `Result<Self, Error>`. It's useful for software where user can set parameters for distributions. Without this kind of methods I have to repeat checks. For release the checking is lost at all. Library uses `debug_assert` which can panic during testing, but it's better to provide explicit behaviour.

I offer to **add** something like this:
```rust
// categorical.rs

pub enum Error {
    LessThanZero,
    GreaterThanOne,
    SumNotEqualOne,
}

impl Categorical {
    pub fn new_with_check(p: &[f64]) -> Result<Self, Error>;
}
```

@IvanUkhov Your opinion?

**Comment by IvanUkhov** [comment]
Thanks for the issue! It was a deliberate decision to panic instead of returning `Result`. The reasoning is that it’s the same type of error as, for instance, index out of bound. That is, it’s a programming mistake, misuse of the API. You usually want to use `Result` when something unexpected might happen, something that is beyond the user’s control such as I/O-related problems. The border line between the two cases is often very thin, but for now I’d rather stay on the programming-mistake side in this crate.

What is questionable right now is whether it should be `debug_assert` or `assert` so that it panics even in release builds.

**Comment by DenisKolodin** [comment]
I agree in general. I use library in the chain **Rust/server -> Lua -> Rust/probability**. User writes and runs code with a server. I have to use FFI to call `probability` lib from Lua. If it panics I take **undefined behavior**.

It happens if user set wrong arguments in the Lua code. I can check args for every distribution, but it's odd.
You are right that it's a mistake of a developer/user and better to stop execution. `Result` is suitable, but panics is enough too if I use `catch_unwind`. I've checked the last, it works, but panics hides in the releases. It's better to make panics explicit or provide feature to do it.

If you haven't objections let's fix ambiguous panics in debug and releases modes. Two variants:

1. Add **feature** `panic-always`
2. Change `debug_assert!` to `assert!`

I like the second, because it looks like *division by zero* behavior. With this we close the door to any silent mistake.

**Comment by IvanUkhov** [comment]
I like the second option too, but let’s discuss first what you’re going to do with it.

Can you please elaborate more on your undefined behavior and on how you plan to avoid it? So you call a Rust function from Lua, and that function panics. Do you mean that the call from Lua to Rust finishes successfully, and you cannot tell on the Lua side that something went wrong on the Rust side? Are you planning to catch exceptions on the Rust side using `catch_unwind` and propagate them to Lua in a meaningful way? Is that correct?

**Comment by DenisKolodin** [comment]
That's right!

I want to stop panic and transfer error to Lua with [`lua_error`](https://www.lua.org/manual/5.3/manual.html#lua_error) call (also it helps to show a line number with a mistake in the Lua source). Rust's panics can't unwind correctly, because panic falls into Lua runtime which has another memory layout and gives segfaults.
I've found this about ff and panics only: https://doc.rust-lang.org/book/ffi.html#ffi-and-panics
But I think it's expensive to create thread for every probability generating.

Example part of macro which makes external function for Lua runtime:
```rust
unsafe extern "C" fn $distribution_functino(ls: *mut lua_State) -> c_int {
    let mut state = State::from_ptr(ls);
    let ($($arg,)+) = convert_arguments!(state, $($vt),+);
    let dist = catch_unwind(|| {
        $distribution::new($($arg as $vt)),+)
    });
    match dist {
        Ok(dist) => {
            let value = state.with_extra_typed::<Context>(|context| {
                dist.sample(&mut context.source);
            });
            state.push_number(value as f64);
            1
        },
        Err(e) => {
            let msg = match_cast!( e {
                val as &'static str => format!("{}", val),
                val as String => format!("{}", val),
            });
            if let Some(ref msg) = msg {
                state.error(msg);
            } else {
                state.error("unknown panic");
            }
        },
    }
}
```
When Lua calls this function I use `catch_unwind` to stop panic and convert it to Lua's error.

**Comment by IvanUkhov** [comment]
I see. I hope you’re familiar with the implications of `catch_unwind` and friends. Have a look at the first paragraph in [this blog post](https://blog.rust-lang.org/2016/07/07/Rust-1.10.html) under “What’s in 1.10 stable.”

I perfectly understand why you don’t want to do sanity checks in your code for each distribution individually, but I personally would swallow my pride and do just that if I had to implement something like what you have; `catch_unwind` doesn’t feel right. Yes, the checks would have to be my wrapping code, and they’d have to be kept in sync with the ones in `probability`, but at least it’d be clear, without any unwrapping magic. In order to keep the code ergonomic, I’d augment your macro to have an interface similar to the one below:

```rust
implement! {
    Bernoulli |p| { p > 0.0 && p < 1.0 },
    Beta |alpha, beta, a, b| { alpha > 0.0 && beta > 0.0 && a < b },
    Binomial |n, p| { 0.0 < p && p < 1.0 },
}
```

It’s still pretty dry and reads well.

**Comment by DenisKolodin** [comment]
I saw it, but had not thought about it. You are right. `catch_unwind` makes code unflexible. And it's bad long-term strategy.

I use explicit check for *division by zero* for some calculations. I will follow your approach and check arguments before creating distributions. First profit: I can detect kind of error. Second: it looks consistent with my non-zero checks. And the reason why some distributions can't accept zeros (or other values) is division too.

Ok, we still use panics, because wrong distribution argument isn't temporary error like database connection error. It's resonable for calculations. You can close this issue.

Thanks four your help! It was very valuable to me!
